name: Build y Deploy
 
on:
  push:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Ingreso a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tp-devops-2025:main

  deploy-render:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Llamar al Deploy Hook de Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"